package dev.termestra.tasks.application.service;

import java.util.List;

/** Canonical workspace-local recovery guide for Termestra agents. */
public final class TeamProtocolDocument {
    private static final List<String> ORCHESTRATOR_RULES = List.of(
            "派工前执行 `team list`，只向当前 Workspace 中可见的成员派工。",
            "短小、低风险、不可并行的工作可以直接完成；长时间、跨文件、独立评审或测试工作应拆分。",
            "每个派单给出唯一负责人、明确范围和可验证的交付结果。",
            "用 `team send <worker-name> \"<task>\"` 创建派单；隐藏代理不会进入 Termestra 的状态与审计记录。",
            "角色或容量不足时说明缺口，由用户决定添加或启动成员。",
            "方向改变时用 `team cancel --dispatch <id> \"<reason>\"` 关闭失效工作。",
            "终端末行只是运行信号；正式结果只来自带 Dispatch ID 的成员汇报。"
    );
    private static final List<String> WORKER_RULES = List.of(
            "只处理分配给当前成员的任务，不再转派或启动不可见执行者。",
            "执行中的进度使用 `team status`，任务结束使用 `team report --dispatch <id>`。",
            "汇报必须包含结果、验证证据、修改范围以及未解决风险。",
            "没有有效派单时保持待命，不把普通终端输出伪装成正式结果。"
    );

    private TeamProtocolDocument() { }

    public static String content() {
        return String.join("\n",
                "# Termestra Team Protocol",
                "",
                "This file is auto-generated by Termestra whenever this workspace is opened.",
                "If the agent lost context after `/compact` or internal summarization,",
                "`cat .termestra/PROTOCOL.md` to re-anchor.",
                "",
                "## Runtime model",
                "",
                "Termestra manages each visible member as a real local CLI process.",
                "The `team` command is the durable coordination channel; terminal text is not.",
                "",
                "## Roles",
                "",
                "- **Orchestrator** — owns user communication, decomposition and verification",
                "- **Worker** — owns one assigned scope and returns evidence",
                "",
                "## `team` CLI — orchestrator",
                "",
                "- `team list` — show workspace members and their status",
                "- `team send <worker-name> \"<task>\"` — dispatch by worker name",
                "- `team cancel --dispatch <id> \"<reason>\"` — cancel an open dispatch",
                "",
                "## `team` CLI — worker",
                "",
                "- `team report \"<result>\" --dispatch <id>` — report task outcome",
                "- `team report --stdin --dispatch <id>` — read a long report from stdin",
                "- `team status \"<state>\"` — update the orchestrator when no dispatch is active",
                "",
                "## Guide: dispatch",
                "",
                "Refresh the roster immediately before dispatching and address a visible member by name.",
                "A useful task specifies outcome, boundaries, evidence and file ownership.",
                "Independent tasks may run concurrently; overlapping writes require sequencing.",
                "Cancel obsolete work explicitly so its history remains explainable.",
                "",
                "## Guide: tasks",
                "",
                "Use `.termestra/tasks.md` for the current plan, dependencies and blockers.",
                "Advance work only from verified evidence; distinguish done, blocked and unverified items.",
                "",
                "## Guide: member",
                "",
                "Use `team status` for readiness or progress and `team report` for an assignment outcome.",
                "Reports are evidence, not authority; independently check high-impact claims.",
                "",
                "## Guide: core",
                "",
                "Termestra owns member identity, Dispatch state and the audit trail; the selected CLI supplies reasoning and execution.",
                "Only visible members participate in team coordination and status accounting.",
                "",
                "## Orchestrator rules",
                "",
                render(ORCHESTRATOR_RULES),
                "",
                "## Worker rules",
                "",
                render(WORKER_RULES),
                "",
                "## In-message reminders",
                "",
                "Messages received in this workspace end with a short",
                "`<termestra-system-reminder>` block. Re-read this file if more context is needed.",
                "");
    }

    private static String render(List<String> rules) {
        return rules.stream().map(rule -> "- " + rule).reduce((left, right) -> left + "\n" + right).orElse("");
    }
}
