package dev.termestra.execution.adapter.in.http;
import com.fasterxml.jackson.annotation.JsonProperty;import dev.termestra.execution.application.exception.RunNotFound;import dev.termestra.execution.application.port.in.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import reactor.core.publisher.Mono;import reactor.core.scheduler.Schedulers;import java.nio.file.Path;import java.util.*;
@RestController public final class WorkspaceShellController {private final AgentExecutionUseCase execution;public WorkspaceShellController(AgentExecutionUseCase execution){this.execution=execution;}
 @PostMapping("/api/workspaces/{workspaceId}/shell/start") @ResponseStatus(HttpStatus.CREATED) Mono<ShellResponse> start(@PathVariable String workspaceId,org.springframework.http.server.reactive.ServerHttpRequest request){return blocking(()->{String id=workspaceId+":shell";ShellLaunch shell=defaultShell(System.getProperty("os.name",""),System.getenv());execution.configure(new ConfigureAgentCommand(workspaceId,id,shell.command(),shell.arguments(),null,null));AgentRunView run=execution.start(new StartAgentCommand(workspaceId,id,Integer.toString(Objects.requireNonNull(request.getLocalAddress()).getPort())));return new ShellResponse(id,"Shell",run.runId(),run.status(),"default");});}
 @DeleteMapping("/api/workspaces/{workspaceId}/shell/{runId}") @ResponseStatus(HttpStatus.NO_CONTENT) Mono<Void> close(@PathVariable String workspaceId,@PathVariable String runId){return blocking(()->{AgentRunView run=execution.get(runId);if(!run.agentId().equals(workspaceId+":shell"))throw new RunNotFound("Shell run not found");execution.forgetRun(runId);return null;});}
 private static <T>Mono<T> blocking(java.util.concurrent.Callable<T> work){return Mono.fromCallable(work).subscribeOn(Schedulers.boundedElastic());}
 static ShellLaunch defaultShell(String osName,Map<String,String> environment){if(osName.toLowerCase(Locale.ROOT).contains("win"))return new ShellLaunch(environment.getOrDefault("ComSpec","cmd.exe"),List.of());String shell=Objects.requireNonNullElse(environment.get("SHELL"),"/bin/sh");String name=Path.of(shell).getFileName().toString().toLowerCase(Locale.ROOT);return new ShellLaunch(shell,Set.of("bash","fish","ksh","zsh").contains(name)?List.of("-l"):List.of());}
 record ShellLaunch(String command,List<String> arguments){}
 record ShellResponse(@JsonProperty("agent_id")String agentId,@JsonProperty("agent_name")String agentName,@JsonProperty("run_id")String runId,String status,@JsonProperty("terminal_input_profile")String terminalInputProfile){}
}
