package dev.termestra.configuration.adapter.in.http;
import com.fasterxml.jackson.annotation.JsonProperty;import dev.termestra.configuration.application.port.in.*;import dev.termestra.configuration.domain.model.*;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;import reactor.core.publisher.Mono;import reactor.core.scheduler.Schedulers;import java.nio.file.*;import java.util.*;
@RestController public final class SettingsController {
 private final ConfigurationUseCase settings;private final CommandAvailabilityUseCase availability;public SettingsController(ConfigurationUseCase settings,CommandAvailabilityUseCase availability){this.settings=settings;this.availability=availability;}
 @GetMapping("/api/ui/settings/command-presets") Mono<List<CommandPresetSummaryResponse>> commandSummaries(){return blocking(()->settings.commandPresets().stream().map(value->CommandPresetSummaryResponse.from(value,availability)).toList());}
 @GetMapping("/api/settings/command-presets") Mono<List<CommandPresetResponse>> commands(){return blocking(()->settings.commandPresets().stream().map(value->CommandPresetResponse.from(value,availability)).toList());}
 @PostMapping("/api/settings/command-presets") @ResponseStatus(HttpStatus.CREATED) Mono<CommandPresetResponse> createCommand(@RequestBody CommandPresetRequest body){return blocking(()->CommandPresetResponse.from(settings.createCommandPreset(body.value()),availability));}
 @PatchMapping("/api/settings/command-presets/{id}") Mono<CommandPresetResponse> updateCommand(@PathVariable String id,@RequestBody CommandPresetRequest body){return blocking(()->CommandPresetResponse.from(settings.updateCommandPreset(id,body.value()),availability));}
 @DeleteMapping("/api/settings/command-presets/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) Mono<Void> deleteCommand(@PathVariable String id){return blocking(()->{settings.deleteCommandPreset(id);return null;});}
 @GetMapping("/api/ui/settings/role-templates") Mono<List<RoleTemplateSummaryResponse>> roleSummaries(){return blocking(()->settings.roleTemplates().stream().map(RoleTemplateSummaryResponse::from).toList());}
 @GetMapping("/api/settings/role-templates") Mono<List<RoleTemplateResponse>> roles(){return blocking(()->settings.roleTemplates().stream().map(RoleTemplateResponse::from).toList());}
 @PostMapping("/api/settings/role-templates") @ResponseStatus(HttpStatus.CREATED) Mono<RoleTemplateResponse> createRole(@RequestBody RoleTemplateRequest body){return blocking(()->RoleTemplateResponse.from(settings.createRoleTemplate(body.value())));}
 @PatchMapping("/api/settings/role-templates/{id}") Mono<RoleTemplateResponse> updateRole(@PathVariable String id,@RequestBody RoleTemplateRequest body){return blocking(()->RoleTemplateResponse.from(settings.updateRoleTemplate(id,body.value())));}
 @DeleteMapping("/api/settings/role-templates/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) Mono<Void> deleteRole(@PathVariable String id){return blocking(()->{settings.deleteRoleTemplate(id);return null;});}
 @GetMapping("/api/settings/app-state/{key}") Mono<Map<String,Object>> appState(@PathVariable String key){return blocking(()->{Map<String,Object> result=new LinkedHashMap<>();result.put("key",key);result.put("value",settings.appState(key).orElse(null));return result;});}
 @PutMapping("/api/settings/app-state/{key}") @ResponseStatus(HttpStatus.NO_CONTENT) Mono<Void> appState(@PathVariable String key,@RequestBody AppStateRequest body){return blocking(()->{settings.setAppState(key,body.value());return null;});}
 private static <T>Mono<T> blocking(java.util.concurrent.Callable<T> action){return Mono.fromCallable(action).subscribeOn(Schedulers.boundedElastic());}
 public record CommandPresetRequest(@JsonProperty("display_name")String displayName,String command,List<String> args,Map<String,String> env,@JsonProperty("resume_args_template")String resumeArgsTemplate,@JsonProperty("session_id_capture")Map<String,Object> sessionIdCapture,@JsonProperty("yolo_args_template")List<String> yoloArgsTemplate){CommandPreset value(){return new CommandPreset(null,Objects.requireNonNullElse(displayName,""),Objects.requireNonNullElse(command,""),args,env,resumeArgsTemplate,sessionIdCapture,yoloArgsTemplate,false);}}
 public record CommandPresetSummaryResponse(String id,@JsonProperty("display_name")String displayName,String command,List<String> args,boolean available){static CommandPresetSummaryResponse from(CommandPreset value,CommandAvailabilityUseCase availability){return new CommandPresetSummaryResponse(value.id(),ConfigurationInputLimits.boundedDisplayName(value.displayName()),ConfigurationInputLimits.boundedCommand(value.command()),ConfigurationInputLimits.boundedArguments(value.arguments()),availability.available(value));}}
 public record CommandPresetResponse(String id,@JsonProperty("display_name")String displayName,String command,List<String> args,Map<String,String> env,@JsonProperty("resume_args_template")String resumeArgsTemplate,@JsonProperty("session_id_capture")Map<String,Object> sessionIdCapture,@JsonProperty("yolo_args_template")List<String> yoloArgsTemplate,@JsonProperty("is_builtin")boolean builtin,boolean available){static CommandPresetResponse from(CommandPreset value,CommandAvailabilityUseCase availability){return new CommandPresetResponse(value.id(),ConfigurationInputLimits.boundedDisplayName(value.displayName()),ConfigurationInputLimits.boundedCommand(value.command()),ConfigurationInputLimits.boundedArguments(value.arguments()),ConfigurationInputLimits.boundedEnvironment(value.environment()),ConfigurationInputLimits.boundedResumeTemplate(value.resumeArgsTemplate()),ConfigurationInputLimits.boundedSessionCapture(value.sessionIdCapture()),value.yoloArgsTemplate()==null?null:ConfigurationInputLimits.boundedArguments(value.yoloArgsTemplate()),value.builtin(),availability.available(value));}}
 public record RoleTemplateRequest(String name,@JsonProperty("role_type")String roleType,String description,@JsonProperty("default_command")String defaultCommand,@JsonProperty("default_args")List<String> defaultArgs,@JsonProperty("default_env")Map<String,String> defaultEnv){RoleTemplate value(){return new RoleTemplate(null,Objects.requireNonNullElse(name,""),Objects.requireNonNullElse(roleType,"custom"),Objects.requireNonNullElse(description,""),Objects.requireNonNullElse(defaultCommand,""),defaultArgs,defaultEnv,false);}}
 public record RoleTemplateSummaryResponse(String id,String name,@JsonProperty("role_type")String roleType,String description,@JsonProperty("is_builtin")boolean builtin){static RoleTemplateSummaryResponse from(RoleTemplate value){return new RoleTemplateSummaryResponse(value.id(),ConfigurationInputLimits.boundedRoleName(value.name()),ConfigurationInputLimits.boundedRoleType(value.roleType()),ConfigurationInputLimits.boundedRoleDescription(value.description()),value.builtin());}}
 public record RoleTemplateResponse(String id,String name,@JsonProperty("role_type")String roleType,String description,@JsonProperty("default_command")String defaultCommand,@JsonProperty("default_args")List<String> defaultArgs,@JsonProperty("default_env")Map<String,String> defaultEnv,@JsonProperty("is_builtin")boolean builtin){static RoleTemplateResponse from(RoleTemplate value){return new RoleTemplateResponse(value.id(),ConfigurationInputLimits.boundedRoleName(value.name()),ConfigurationInputLimits.boundedRoleType(value.roleType()),ConfigurationInputLimits.boundedRoleDescription(value.description()),ConfigurationInputLimits.boundedCommand(value.defaultCommand()),ConfigurationInputLimits.boundedArguments(value.defaultArguments()),ConfigurationInputLimits.boundedEnvironment(value.defaultEnvironment()),value.builtin());}}
 public record AppStateRequest(String value){}
}
