package dev.termestra.bootstrap;
import org.junit.jupiter.api.Test;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.server.LocalServerPort;import org.springframework.http.HttpHeaders;import org.springframework.test.context.*;import org.springframework.test.web.reactive.server.WebTestClient;import java.io.IOException;import java.nio.file.*;import java.util.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT) class SettingsMarketplaceHttpIntegrationTest {
 private static final Path DATA=temp();@DynamicPropertySource static void properties(DynamicPropertyRegistry registry){registry.add("termestra.data-directory",DATA::toString);}@LocalServerPort int port;
 @Test void runsSettingsCrudAndReadsBundledMarketplace(){WebTestClient client=WebTestClient.bindToServer().baseUrl("http://127.0.0.1:"+port).build();String cookie=cookie(client);
  List<Map> builtins=client.get().uri("/api/settings/command-presets").header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isOk().expectBodyList(Map.class).returnResult().getResponseBody();
  assertPresetIds(builtins);
  List<Map> summaries=client.get().uri("/api/ui/settings/command-presets").header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isOk().expectBodyList(Map.class).returnResult().getResponseBody();
  assertPresetSummaries(summaries);
  List<Map> roleSummaries=client.get().uri("/api/ui/settings/role-templates").header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isOk().expectBodyList(Map.class).returnResult().getResponseBody();
  assertRoleSummaries(roleSummaries);
  Map<?,?> preset=client.post().uri("/api/settings/command-presets").header(HttpHeaders.COOKIE,cookie).bodyValue(Map.of("display_name","Local Agent","command","/bin/cat","args",List.of(),"env",Map.of())).exchange().expectStatus().isCreated().expectBody(Map.class).returnResult().getResponseBody();String presetId=Objects.requireNonNull(preset).get("id").toString();
  client.patch().uri("/api/settings/command-presets/"+presetId).header(HttpHeaders.COOKIE,cookie).bodyValue(Map.of("display_name","Updated Agent","command","/bin/cat","args",List.of(),"env",Map.of())).exchange().expectStatus().isOk().expectBody().jsonPath("$.display_name").isEqualTo("Updated Agent");
  client.delete().uri("/api/settings/command-presets/"+presetId).header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isNoContent();
  client.put().uri("/api/settings/app-state/active_workspace_id").header(HttpHeaders.COOKIE,cookie).bodyValue(Map.of("value","workspace-1")).exchange().expectStatus().isNoContent();
  client.get().uri("/api/settings/app-state/active_workspace_id").header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isOk().expectBody().jsonPath("$.value").isEqualTo("workspace-1");
  client.get().uri("/api/marketplace/manifest?lang=zh").header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isOk().expectBody().jsonPath("$.language").isEqualTo("zh").jsonPath("$.agents").isArray();
  client.get().uri(uriBuilder->uriBuilder.path("/api/marketplace/agent").queryParam("lang","en").queryParam("path","design/design-ux-architect.md").build()).header(HttpHeaders.COOKIE,cookie).exchange().expectStatus().isOk().expectBody().jsonPath("$.frontmatter.name").isEqualTo("UX Architect").jsonPath("$.body").value(value->{if(!value.toString().contains("ArchitectUX"))throw new AssertionError("agent body missing");});
 }
 private static void assertPresetIds(List<Map> presets){Set<String> ids=new LinkedHashSet<>();for(Map preset:Objects.requireNonNull(presets)){if(!Boolean.TRUE.equals(preset.get("is_builtin")))throw new AssertionError("expected builtin preset: "+preset);if(!(preset.get("env") instanceof Map))throw new AssertionError("expected preset env: "+preset);ids.add(preset.get("id").toString());}Set<String> expected=Set.of("claude","codex","opencode","gemini","hermes","qwen","pi","agy","cursor","grok");if(!ids.equals(expected))throw new AssertionError("unexpected preset ids: "+ids);}
 private static void assertPresetSummaries(List<Map> presets){Set<String> fields=Set.of("id","display_name","command","args","available","model_picker","revision");for(Map preset:Objects.requireNonNull(presets)){if(!preset.keySet().equals(fields))throw new AssertionError("summary leaked detail fields: "+preset.keySet());if(!(preset.get("model_picker") instanceof Map picker)||!picker.keySet().equals(Set.of("supported","allow_custom","suggested_models")))throw new AssertionError("invalid model picker: "+preset);if(Set.of("cursor","opencode","pi").contains(preset.get("id"))&&(!Boolean.FALSE.equals(picker.get("supported"))||!Boolean.FALSE.equals(picker.get("allow_custom"))||!List.of().equals(picker.get("suggested_models"))))throw new AssertionError("workspace creation exposed worker-only model discovery: "+preset);}}
 private static void assertRoleSummaries(List<Map> roles){Set<String> fields=Set.of("id","name","role_type","description","is_builtin");for(Map role:Objects.requireNonNull(roles))if(!role.keySet().equals(fields))throw new AssertionError("role summary leaked detail fields: "+role.keySet());}
 private static String cookie(WebTestClient client){String header=client.get().uri("/api/ui/session").exchange().expectStatus().isOk().expectBody(Map.class).returnResult().getResponseHeaders().getFirst(HttpHeaders.SET_COOKIE);return Objects.requireNonNull(header).substring(0,header.indexOf(';'));}private static Path temp(){try{return Files.createTempDirectory("termestra-settings-");}catch(IOException error){throw new ExceptionInInitializerError(error);}}
}
