spring.application.name=termestra
termestra.version=@project.version@
server.address=127.0.0.1
server.port=${TERMESTRA_PORT:3000}
termestra.data-directory=${TERMESTRA_DATA_DIRECTORY:${TERMESTRA_DATA_DIR:${user.home}/.config/termestra}}
spring.codec.max-in-memory-size=1MB
