package dev.termestra.configuration.application.service;
import dev.termestra.configuration.application.port.in.*;import dev.termestra.configuration.application.port.out.ConfigurationRepository;import dev.termestra.configuration.domain.model.*;import java.time.*;import java.util.*;
public final class ConfigurationApplicationService implements ConfigurationUseCase {
 private final ConfigurationRepository repository;private final Clock clock;public ConfigurationApplicationService(ConfigurationRepository repository,Clock clock){this.repository=repository;this.clock=clock;}
 @Override public List<CommandPreset> commandPresets(){return repository.commandPresets();}
 @Override public CommandPreset createCommandPreset(CommandPreset value){ConfigurationInputLimits.validate(value);CommandPreset created=new CommandPreset(UUID.randomUUID().toString(),value.displayName(),value.command(),value.arguments(),value.environment(),value.resumeArgsTemplate(),value.sessionIdCapture(),value.yoloArgsTemplate(),false,value.modelCapability(),1);repository.insert(created,Instant.now(clock));return created;}
 @Override public CommandPreset updateCommandPreset(String id,CommandPreset value){ConfigurationInputLimits.validate(value);CommandPreset updated=new CommandPreset(id,value.displayName(),value.command(),value.arguments(),value.environment(),value.resumeArgsTemplate(),value.sessionIdCapture(),value.yoloArgsTemplate(),false,value.modelCapability(),Math.max(1,value.revision()));requireChanged(repository.update(updated,Instant.now(clock)),"command preset",id);return command(id);}
 @Override public void deleteCommandPreset(String id){requireChanged(repository.deleteCommandPreset(id),"command preset",id);}
 @Override public List<RoleTemplate> roleTemplates(){return repository.roleTemplates();}
 @Override public RoleTemplate createRoleTemplate(RoleTemplate value){ConfigurationInputLimits.validate(value);RoleTemplate created=new RoleTemplate(UUID.randomUUID().toString(),value.name(),value.roleType(),value.description(),value.defaultCommand(),value.defaultArguments(),value.defaultEnvironment(),false);repository.insert(created,Instant.now(clock));return created;}
 @Override public RoleTemplate updateRoleTemplate(String id,RoleTemplate value){ConfigurationInputLimits.validate(value);RoleTemplate updated=new RoleTemplate(id,value.name(),value.roleType(),value.description(),value.defaultCommand(),value.defaultArguments(),value.defaultEnvironment(),false);requireChanged(repository.update(updated,Instant.now(clock)),"role template",id);return updated;}
 @Override public void deleteRoleTemplate(String id){requireChanged(repository.deleteRoleTemplate(id),"role template",id);}
 @Override public Optional<String> appState(String key){return repository.appState(requireStateKey(key));}@Override public void setAppState(String key,String value){String safeKey=requireStateKey(key);if(value!=null&&value.length()>65_536)throw new IllegalArgumentException("Application state value exceeds 65536 characters");repository.setAppState(safeKey,value,Instant.now(clock));}
 private static String requireStateKey(String key){if(key==null||key.isBlank())throw new IllegalArgumentException("Application state key is required");if(key.length()>256)throw new IllegalArgumentException("Application state key exceeds 256 characters");return key;}
 private static void requireChanged(ConfigurationRepository.MutationResult result,String type,String id){if(result==ConfigurationRepository.MutationResult.READ_ONLY)throw new ConfigurationConflict("Builtin "+type+" is read-only: "+id);if(result==ConfigurationRepository.MutationResult.NOT_FOUND)throw new ConfigurationNotFound(Character.toUpperCase(type.charAt(0))+type.substring(1)+" not found: "+id);}
 private CommandPreset command(String id){return commandPresets().stream().filter(item->item.id().equals(id)).findFirst().orElseThrow(()->new ConfigurationNotFound("Command preset not found: "+id));}
 private RoleTemplate role(String id){return roleTemplates().stream().filter(item->item.id().equals(id)).findFirst().orElseThrow(()->new ConfigurationNotFound("Role template not found: "+id));}
}
